autopatch:
  schedule: "0 2 * * *"
  container_runtime: "podman"
  registries:
    dockerhub:
      username: ""
      password: ""
  notifications:
    email:
      enabled: false
      smtp_server: "smtp.gmail.com"
      smtp_port: 587
      sender_email: ""
      sender_password: ""
      recipient_email: ""
  logging:
    log_level: "INFO"
    log_file: "logs\\autopatch.log"
    report_dir: "logs\\reports"
  containers:
    exclude: []